.TH PACMAN-DB-UPGRADE "8" "August 2022" "pacman"
.SH NAME
pacman-db-upgrade \- Upgrade the local pacman database to a newer format
.SH SYNOPSIS
.B pacman-db-upgrade
[\fIoptions\fR]
.SH DESCRIPTION
.B pacman-db-upgrade
upgrades the local pacman database to a newer format.
.SH OPTIONS
.TP
.BR \-d ", " \-\-dbpath " " \fIpath\fR
Set an alternate database location.
.TP
.BR \-h ", " \-\-help
Show the program's built-in help message and exit.
.TP
.BR \-r ", " \-\-root " " \fIpath\fR
Set an alternate installation root.
.TP
.BR \-V ", " \-\-version
Show version information and exit.
.TP
.B \-\-config\fR \fIpath\fR
Set an alternate configuration file.
.TP
.B \-\-nocolor
Disable colorized output messages.
.SH COPYRIGHT
Copyright \(co 2010-2021 Pacman Development Team <pacman-dev@archlinux.org>.
.PP
.br
This is free software; see the source for copying conditions.
There is NO WARRANTY, to the extent permitted by law.
