.TH TESTPKG "8" "August 2022" "pacman"
.SH NAME
testpkg \- test a pacman package for validity
.SH SYNOPSIS
.B testpkg
.I package-file
.SH DESCRIPTION
.B testpkg
tests a package made by \fBmakepkg\fR(8) for validity.
.SH COPYRIGHT
Copyright \(co 2010-2021 Pacman Development Team <pacman-dev@archlinux.org>.
.PP
.br
This is free software; see the source for copying conditions.
There is NO WARRANTY, to the extent permitted by law.
